### ISSUE TITLE
a few suggestion

### ISSUE THREAD

**Issue by mvkrdndm** [lukasmonk/lucaschess#10]
hello ,
1- if there would be an option to for available moves and stuff .it would be better instead of forcing to show them always,etc in blind chess when you hold a piece it show where is can be move it is kinda cheating for me ( i mean in the picture this little signs i mention about if i could not tell properly piece movements attacked pieces little hints unnecessary and disturbing)
2- i want to analyse a game freely like in lichess i mean i can move and see with my eyes my combination how strong but in lucas chess it is very hard to do so you can add variations to pgn but it is time consuming if you have time please try to free analysing with your own eyes you can move pieces freely and create your own variations easly.
3- in lichess the engine also shows the best move in visually it is also good instead of reading the best move from engine output it can auto arrow the best move.it should be nice if there is an option to we can see the best move in the chess board ,i tried to show on the picture.
also i put the lichess analyse windows if you interested please check lichess play a game and analyse it it is so easy you can input your own variations to it so easly.
note : well my knight arrow was wrong i realized later,it shows Nd7 instead of Rad8 pardon me
![image 003](https://cloud.githubusercontent.com/assets/16892782/14796120/6280b7de-0b34-11e6-9f8f-a307b9e0427b.jpg)
![image 004](https://cloud.githubusercontent.com/assets/16892782/14796453/08113164-0b36-11e6-8076-ff41e547971a.jpg)

**Comment by lukasmonk** [comment]
Hi,
1. When playing, these litle symbols appear when it is configurated in Options-Configuration-Boards-Show candidates. When showing a game they appear if you press a pieze.
2. Yes, perhaps in future I will include this feature.
3. When showing a game, I coud add an engine to work in the background.

I note your ideas.
Thak you very much

**Comment by mvkrdndm** [comment]
thanks for answer.in number 3 yes we can add kibitzer best in one line in the screenshot there it exist and it works perfect only  if it points the strongest line visually like in lichess ,when analysing a pgn .great product it is best chess software thanks for your efforts
