### ISSUE TITLE
Engine does not respond after some moves

### ISSUE THREAD

**Issue by Stochastic13** [lukasmonk/lucaschess#100]
Opponent: **Ufim 8.02 (1000)**, version: **11.15a portable & 11.15 portable**, platform: **Windows i7**

After playing a few moves, no matter what my move, the engine does not respond. The black hand signifying the opponent "thinking" comes and goes without the actual move. The red dot at the top left corner stays there until I minimize and maximize again, after which the dot turns white and comes to the bottom right (signifying my move) without there being any move on black's side. Same thing happens with many different openings. Posting one random example below.

Just after my move:
![image](https://user-images.githubusercontent.com/28253514/53401514-f56eb000-39d5-11e9-86a5-861487d98679.png)

After minimizing and maximizing:

![image](https://user-images.githubusercontent.com/28253514/53401536-fef81800-39d5-11e9-9adf-ed80358cf4ea.png)

**Comment by lukasmonk** [comment]
I haven't been able to replicate the problem.

**Comment by Stochastic13** [comment]
I am having the problem every time with the same settings. I am running it with the depth at 5, if that makes a difference.

**Comment by lukasmonk** [comment]
It's a problem with Ufim. It is not compatible the depth limit and the limit elo, or one or the other, not both.
