### ISSUE TITLE
greyed "time" setting for "game against engine" configuration

### ISSUE THREAD

**Issue by Trokinos** [lukasmonk/lucaschess#101]
Hello

Using the portable version of Lucas Chess 11.15a 
If i go to Play -> Play a game against an engine of your choice" , i am unable to change the time setting for the opponent as shown in that screenshot :

https://i.imgur.com/7mbQUUX.jpg

I tried  changing the engine but it seems to make no difference : the time setting is still greyed for each of them.

**Comment by lukasmonk** [comment]
First, you must change the depth to -.

**Comment by Trokinos** [comment]
Thank you for the solution, i didn't knew both settings were mutually exclusives.
So as it's not an issue i am closing it.

**Comment by lukasmonk** [comment]
I´ll try to change this, to be more usable.
