### ISSUE TITLE
'Takeback' after 'Utilities -> play current position' does not work 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschess#107]
If one has set up a game and chosen to play the current position against an engine, and then one does a take back, then one cannot play another move. Or at least that is what I found initially; upon revisiting the window, I found I could play both black and white pieces. I found further that repeatedly pressing 'takeback' took me back a certain number of moves and then stopped - at a position that was several moves on from the starting position that I had set up. Also, for some reason I ended up seemingly have several games running simultaneously.

All this may be user error. If so, I submit that the UI should be clearer.

Lucas Chess 11.16 (on Windows 10 1903).

**Comment by lukasmonk** [comment]
Perhaps this can help, at least to detect the problem:
[2020-01-07-17-12-31.zip](https://github.com/lukasmonk/lucaschess/files/4031439/2020-01-07-17-12-31.zip)

**Comment by LinuxOnTheDesktop** [comment]
Thanks for that video. I was going to record my own video showing what seemed to be going wrong for me. But then I found that the problem - or at least a problem - began earlier. For, here is what happened.

1. I ran LucasChess.
2. I chose 'Tools' -> 'Create your own game'.
3. I made a white move.
4. I made a black move.
5. 'Utilities' -> 'Play current position'.

And upon that last step _the program undid the black move_. Perhaps I just fail - fairly grossly - to understand the interface.

**Comment by lukasmonk** [comment]
[Code.zip](https://github.com/lukasmonk/lucaschess/files/4035974/Code.zip)
Unzip this and copy both files to the Code folder, then you can try it out.

**Comment by LinuxOnTheDesktop** [comment]
Thanks, but try just what out, and why, and how? You've sent me two Python files; I don't know what you wish me to do with them.

**Comment by lukasmonk** [comment]
Copy both files in the installation folder of LucasChess, to the Code folder.

**Comment by LinuxOnTheDesktop** [comment]
Ah, so you wish me to test a would-be fix? OK. The fix . . seems to work! Still, some other strange things seemed to happen, namely (1) being prompted to save the game after I had save it), and (2) it being my move - when playing a position that I had created, playing it against the computer but the computer not allowing me to move. However, 1 and 2 may owe to user error; I am having trouble reproducing them.
