### ISSUE TITLE
'Takeback' after 'Utilities -> play current position': 'take back' takes back one's opponent's move

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschess#108]
**To reproduce the problem**

Have Lucas Chess 11.17 installed (on Windows 10).
Create own game -> play current position.
Try to take back a move.

**The result**

The program takes back _your opponent's_ move; if you wish to take back _your_ move, you need to press 'take back' again. 

**Expected behaviour**

One expects that, as in other modes of the program, one's _own move_ will be taken back (taken back _without further ado_).

**Comment by lukasmonk** [comment]
Fixed. If you want to test, unzip and copy GestorSolo.py to the folder Code in the installation of the program: 
[GestorSolo.zip](https://github.com/lukasmonk/lucaschess/files/4113184/GestorSolo.zip)

**Comment by LinuxOnTheDesktop** [comment]
That seems to fix the problem. Well done and thank you. However, I notice that when one follows the steps that I gave ('To reproduce the problem'), the program does not honour the animation speed that I have set. For, I have set the animation of the piece movement to be moderately slow; yet, when I play a game in the fashion indicated, the animation is very fast. Can you reproduce that problem?

**Comment by lukasmonk** [comment]
"Create your own game" is an option designed to work in games and positions, not to play, so I have not worried about including visual effects.
