### ISSUE TITLE
Feature request: have option not to move the King automatically when his move is forced

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschess#109]
In Lucas Chess 11.17, and unless I make some mistake, if I must move my King - because of check, say - and can move him to only one square, then, upon touching the King, the computer moves him. I would like an option to disable that automatic moving.

**Comment by lukasmonk** [comment]
With this configuration;
![image](https://user-images.githubusercontent.com/6254278/73131296-e1c63200-4008-11ea-95ed-22ca6f40972e.png)

I am unable to replicate the problem in the following example:
FEN: k7/1p1p4/8/8/3b1B2/8/P1P5/K7 w - - 0 1

![image](https://user-images.githubusercontent.com/6254278/73131329-7af54880-4009-11ea-9800-831b39aca081.png)

**Comment by LinuxOnTheDesktop** [comment]
Thank you for your work.

Are there not _two_ possible moves for white here, though? Namely, Kb1 and c3. (I apologise if I miss something. I fail to understand the notion - 'k7/1p1p4' etc. - that you give.)

**Comment by lukasmonk** [comment]
Yes, bad example. Remove c2 pawn and test it.
k7/1p1p4/..... is in FEN notation, a way of indicate a position.
You could copy: k7/1p1p4/8/8/3b1B2/8/P7/K7 w - - 0 1
... then Ctrl V in Create your own game window.

**Comment by LinuxOnTheDesktop** [comment]
I opened LucasChess, chose 'create your own game', pasted the text (wow - that pasting is a nice feature!) and then selected 'play current position'. The program did not ask which side I was to be or whose move it was. When I touched the king, it did not move. However, when I moved the king - to the only legal square (namely, b1) - nothing happened, i.e. there was no move from the other side (black). So I am unsure that the test - of whether touching a king that can move to only one square, moves it - was a proper one.

**Comment by lukasmonk** [comment]
Have you tested, Config/Enable engine ?

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the response. However, I am unsure I understand your question. Are you are saying that in order to get the computer to play, I need to use the Config menu to select 'enable engine'? I have not tried that, and I am afraid that I lack the time to do any more testing at the moment. I will say though that I think that all this stuff - this 'create one's own game' feature - would be better were it more intuitive.

**Comment by lukasmonk** [comment]
Are you are saying that in order to get the computer to play, I need to use the Config menu to select 'enable engine'? : 

Yes. Perhaps I have to remove the other option.

Not easy that all works enough good, to be more intuitive to me is a second level, to be more intutive in general is the third level.

Now I am totally focused on the new version and I am fighting in the first level.

Thank you very much for your tests.
