### ISSUE TITLE
Failure to recognise checkmate

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschess#110]
I played the computer - having not gone in for anything like 'create your own game' - and the engine checkmated me but the program seems to think it is my move, i.e. that I have not been checkmated. I am black. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/72857146-a815c400-3cb4-11ea-8284-cc73601ee069.png)

The fact that I am in _double_ check may be relevant.

Upon reaching this strange situation I clicked around in the move table and that triggered an analysis of the winning move:

![image](https://user-images.githubusercontent.com/47056543/72857168-b5cb4980-3cb4-11ea-91cb-fa4063e04643.png)

Third screenshot: of me, er, offering a draw after I've lost:

![image](https://user-images.githubusercontent.com/47056543/72857216-e0b59d80-3cb4-11ea-98b8-61ce659e0387.png)

Lucas Chess 11.16. Windows 10. Engine: Clarabit.

**Comment by lukasmonk** [comment]
Sorry I don´t understand:
Black only move = Rxd8
Then Qf7#

Engine is playing until Resign or mate/draw.
If you offer a draw, and engine has an easy M2, then it is logic its response: engine doesn't accept....

**Comment by LinuxOnTheDesktop** [comment]
I am sorry: I did not realise Rxd8 was available.
