### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by aha999** [lukasmonk/lucaschess#119]
Add at least one donation method button to Github, so anyone willing can donate.

For example, my nieces (both under 15) who compete, like to play Lucas Chess and you're actively developing lucas chess and making it better, so i'd at least like to pay you a couple of coffees, like others probably might.

Various donation platforms i see other open projects use:
- [LiberaPay](https://liberapay.com/)
- [PayPal](https://www.paypal.com/)
- [Patreon](https://www.patreon.com/)
- [Github Sponsors](https://github.com/sponsors)
- [Ko-fi](https://ko-fi.com/)
- [OpenCollective](https://opencollective.com/)
- [Flattr](https://flattr.com/)

Displaying a sponsor button in your repository: [link](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository)

**Comment by lukasmonk** [comment]
Thank you very much for the idea, but I am happy that the project has nothing to do with money. All the tools I use are free, the only one more expensive is my time.

**Comment by aha999** [comment]
The donations are meant as a thank you for the time that you put into the project. It's just a donate button on a github page.
