### ISSUE TITLE
version 10.alpha.08a  , engine output bug

### ISSUE THREAD

**Issue by mvkrdndm** [lukasmonk/lucaschess#12]
hello i am just installed Lucas Chess version 10.alpha.08a ,and realized engine in 1 line option on kibitzer is not working
![image 006](https://cloud.githubusercontent.com/assets/16892782/14816836/b7adfe74-0bbb-11e6-8477-90d79dc613a3.jpg)

**Comment by lukasmonk** [comment]
I will fix now.

Thanks.
