### ISSUE TITLE
Analysis result grid row height not adjustable etc

### ISSUE THREAD

**Issue by sevenzsu** [lukasmonk/lucaschess#13]
The row height/width/font size are not adjustable for the analysis result grid and the analysis grid. And the board size for the training windows is fix and very small.It makes it very hard to use on my surface pro 4.
![training](https://cloud.githubusercontent.com/assets/16618539/14944106/f93d011e-0fb7-11e6-922c-22e1e35c7912.JPG)
![analysis](https://cloud.githubusercontent.com/assets/16618539/14944105/f93cef62-0fb7-11e6-991c-74255996c49e.JPG)
![analysis_result](https://cloud.githubusercontent.com/assets/16618539/14944107/f93d3c24-0fb7-11e6-82a9-b576f9b55199.JPG)

**Comment by lukasmonk** [comment]
Hi

Yes, it is clear that using fixed fonts is a problem in these cases.
I take note, I´ll try to fix in future.

Cheers
Lucas

From:  sevenzsu
Date:  2016-05-01 22:16
Subject:  [lukasmonk/lucaschess] Analysis result grid row height not adjustable etc (#13)
 
The row height/width/font size are not adjustable for the analysis result grid and the analysis grid. And the board size for the training windows is fix and very small.It makes it very hard to use on my surface pro 4.
