### ISSUE TITLE
It is unclear how to undue theme customisations

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschess#130]
Dear Lucas

I tried to create a decent dark theme for (/within) Lucas Chess. I gave up. But then I could not find how to switch to one of the other themes or to revert all theme options to default. (And this is not to mention that one must look for colour options, not under the appearance tab, but under 'Colours'; and once a game is running one cannot change, well, most things about appearance.)

**Comment by lukasmonk** [comment]
There is a checkbox in the Options/Colors/General window; Reset to default. Mark this then Accept.
This is not enough ?

**Comment by LinuxOnTheDesktop** [comment]
Is is enough. I had not seen it. And I should have closed this issue long ago. I apologise. However, the box at issue is rather small - compare #137 - and indeed with my theming a little hard to see. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/104367808-38c36080-5513-11eb-888e-785a4506216b.png)
