### ISSUE TITLE
How to start the program on linux  ?

### ISSUE THREAD

**Issue by ExtremeCoolDude** [lukasmonk/lucaschess#135]
I just installed it from aur.

 https://aur.archlinux.org/packages/lucaschess-git/ :

![image](https://user-images.githubusercontent.com/50034073/99858709-41a05180-2bb6-11eb-95ab-a2dc177ffb09.png)

However, I cannot find it anywhere. 

How do I start this program ?

**Comment by lukasmonk** [comment]
Lucas.py

**Comment by ExtremeCoolDude** [comment]
Thank you. I found Lucas.py on /opt/lucaschess. However, like the previous discussions here on github, it doesn't want to start up on Linux.  The error message is this which seems to be related to pyqt on python2: 

![image](https://user-images.githubusercontent.com/50034073/99902153-b58c4800-2ce3-11eb-8e6b-e6aa95701f9a.png)


Was worth a shot, anyway. Thanks.
