### ISSUE TITLE
pgn text copy error

### ISSUE THREAD

**Issue by Jonathan003** [lukasmonk/lucaschess#140]
Hi,

I recently discovered GitHub.
This is my first post here.
I use Lucas Chess R 1.02.
I notice a problem when copying game text to past in some other chess GUI like Scid or Chessbase.
It looks like capital letters are written as small letters for the black moves.
Here is an example:
`1.Nf3 c6 2.g3 d5 3.Bg2 nf6 4.O-O nbd7 `
should be
`1.Nf3 c6 2.g3 d5 3.Bg2 Nf6 4.O-O Nbd7 `

I have made a small video capture of it:

https://user-images.githubusercontent.com/40061628/104665265-3c044b00-56d1-11eb-9e31-8fc276427042.mp4

**Comment by lukasmonk** [comment]
Sorry, I forgot to correct it in 1.03, for 1.04.

**Comment by lukasmonk** [comment]
Published 1.04

**Comment by Jonathan003** [comment]
Hi Lukas,

I downloaded and installed version 1.04
I have troubles loading OpeningLines
Here is a video capture:


https://user-images.githubusercontent.com/40061628/104851770-47d15680-58f7-11eb-834f-4e147f27fe76.mp4

**Comment by lukasmonk** [comment]
Thanks Jonathan, published 1.04a

**Comment by Jonathan003** [comment]
Thanks for the quick fix!
