### ISSUE TITLE
search or past a position when browsing opening lines

### ISSUE THREAD

**Issue by Jonathan003** [lukasmonk/lucaschess#141]
Hi,
I use the latest version of Lucas Chess, version R1.06a 
I would like to have an option, to search, or just past a position copied from an other Chess GUI, when browsing Opening Lines.
Like it is possible in Scid when browsing a bin book. 
To easily jump to a position in Opening lines, to see if this position is already covered, or to jump to the position, and delete or ad some candidate moves. So I would like to have an 'edit' menu option, to copy and past FEN positions.

![Screenshot Lucas Chess R](https://user-images.githubusercontent.com/40061628/106451830-6868e700-6487-11eb-86c2-36f197731f5f.png)

Here is a video capture of how this works in Scid:

https://user-images.githubusercontent.com/40061628/106452391-1aa0ae80-6488-11eb-831d-2c9ea2e9be7c.mp4

**Comment by lukasmonk** [comment]
This is old version, LukaschessR project is the active.

**Comment by lukasmonk** [comment]
I add your ideas to my list.

**Comment by Jonathan003** [comment]
Sorry I posted it in the wrong project. I moved it to the LukaschessR project so I close it here.
