### ISSUE TITLE
Request options for making bin books with Polyglot book factory

### ISSUE THREAD

**Issue by Jonathan003** [lukasmonk/lucaschess#142]
![image](https://user-images.githubusercontent.com/40061628/106482913-3f0f8180-64ae-11eb-9b29-6de1dd1a652a.png)
I would like to have a uniform option.
I also would like to have this new option for building bin books. Next to 'Minimum number or games' and 'Minimum score', I would like to have an option to specify how much percentage of the time a move have to be played.
For my white repertoire than, I would for example make a 'only white' book, from I collection of high quality games, and choose the option 'min_percentage=20'. Than I make a 'only black' book, and choose the option 'min_percentage=0.5'
Than I merge white and black books, and I import the book to Opening Lines, and I have my repertoire.

**Comment by lukasmonk** [comment]
I can't think of a way to do it right now.
When exporting to bin there is that uniform option.

**Comment by lukasmonk** [comment]
This is Lucaschess old version, there is no bin factory in this.

**Comment by Jonathan003** [comment]
Ok I edited the post a bit and posted in the Lucas ChessR project. So I have a uniform option already, so my request is to ad an option for 'minimum-percentage' a move have to be played, to be included in the bin book. Like I explain in my post in the Lucas ChessR project.
