### ISSUE TITLE
Please update RodentII chess engine

### ISSUE THREAD

**Issue by stolowski** [lukasmonk/lucaschess#17]
Hi Luca! Could you please update the RodentII chess engine (http://www.pkoziol.cal24.pl/rodent/download.htm)  to the latest 0.9.64 with the next release of LucaChess? Thank you.

**Comment by lukasmonk** [comment]
Hi Pavel
I have already included it in the new update, that I will publish today or tomorrow (I hope).
It is also ( with stockfish 8) in the Linux engines.
