### ISSUE TITLE
Better handle for UCI "type string"

### ISSUE THREAD

**Issue by tico-tico** [lukasmonk/lucaschess#18]
Some engines like Texel 1.06 (http://www.talkchess.com/forum/viewtopic.php?t=60774) don't provide anything after **default** part of the **type string** option assuming default empty string. Something like:

```
option name BookFile type string default
option name UCI_Opponent type string default
option name GaviotaTbPath type string default
```

Now Lucas Chess just ignores this setting and doesn't show it in the GUI. This change
```python
    def leeString(self, li):
        if ( len(li) == 3 or len(li) == 4 ) and li[2] == "default":
            self.default = "" if len(li) == 3 or li[3] == "<empty>" else li[3]
            return True
        else:
            return False
```
in MotoresExternos.py fixes the issue for me.

**Comment by lukasmonk** [comment]
Fixed in my copy with your code, thank you very much.
