### ISSUE TITLE
Long-ish delay upon starting a game on Linux

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [lukasmonk/lucaschess#24]
Lucas Chess takes some five seconds to start a game, i.e. to let me make my first move, on an SSD system that does not have the same delay when running LucasChess under Wine.

Linux Mint 18.1 x64.

**Comment by lukasmonk** [comment]
Development version 11 include support Linux32 y Linux64: [lucaschess_11](https://github.com/lukasmonk/lucaschess_11)
All tests about Linux must be referred to the development version.
I believe that this problem is fixed, at least in my VM Linux Mint 18.1 x64.
