### ISSUE TITLE
Program window has no close button, nor a maximise button, on Linux

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [lukasmonk/lucaschess#26]
Here's a screenshot (of the program when it had hung - see #25 ).

![image](https://cloud.githubusercontent.com/assets/9998846/22047585/dfcb1f64-dd1f-11e6-89a6-7a48e68a1031.png)

Linux Mint 18.1 x64.

**Comment by lukasmonk** [comment]
This is a known problem/difference of behaviour of the library qt in Linux in relation to windows.
I don´t know a way to fix.
To minimize, F12 is a good idea, minimize as a try icon.
To maximize, I have to think about.
