### ISSUE TITLE
10.10.3 always plays same opening . .

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [lukasmonk/lucaschess#27]
. . even when I have set the opening to 'undetermined'. The computer always opens with nf3 or, as black against e3, always plays Nf6. The problem occurs with the Deep Tonga engine and one other engine that I tried.

**Comment by lukasmonk** [comment]
In my PC, with no options in the Initial moves tab, with Deep Toga and time 3s = always d4, with depth 1..3 =d4
This is not something controlled by the GUI, it is the move decided by engine.

You can run toga directly, then write uci<enter>, then go movetime 1000, ....

**Comment by ACinnamonUserInUK** [comment]
> This is not something controlled by the GUI, it is the move decided by engine.

And yet: (1) were this the case, the engine would be a bad one; (2) this was not the case with an earlier version of Lucas Chess that I had.

This problem, and the seemingly 'close-happy' attitude on this bug-tracker, are inclining me towards abandoning Lucas Chess - and ceasing to recommend it to people.

**Comment by lukasmonk** [comment]
I have done the same test again, and deep toga select d4 with depth1, with time=3 d4, with 20 seconds thinking = e4, never Nf3, that is also a good open.
All is unmarqued in your Initial moves tab ?

I need to replicate the problem, but in this moment I can´t. It is necessary more information.

> This problem, and the seemingly 'close-happy' attitude on this bug-tracker, are inclining me towards abandoning Lucas Chess - and ceasing to recommend it to people.

Sorry it is not my intention to disturb you, I have not much experience with this support and obviously it is an error. 
This is for fun to me, and I don´t want to disturb people that want to help me, it has no sense.

Then please help me to undestand the problem, then you decides the better you consider.

**Comment by ACinnamonUserInUK** [comment]
If I may respond - even though the issue is marked - closed: good; please tell me what information you would like me to provide. I have the problem on both Windows and Linux (though admittedly that comes to the same thing really, since the Linux version is running in Wine because the native Linux version is, I am afraid, basically broken).

**Comment by lukasmonk** [comment]
I have reopen the issue, the other day I´ll try to reopen, but I can't.
I need to know which is the option that you use to detect the problem, if is "Playing against any engine", the values of the tab Initial moves.

In relation to Linux, it is not supported in this version.
The next version has a repository here, and supports Linux32 and Linux64.
It has a folder = Linux, an d a script to launch the program.
[lucaschess_11](https://github.com/lukasmonk/lucaschess_11)

Today I have tried to fix a problem that I believe doesn´t have a solucion in Linux, about minimize/maximize in the main window. Other issue you report.

**Comment by ACinnamonUserInUK** [comment]
My in-game configuration is as shown in the images I attach. (The images are from LucasChess running on Linux-under-Wine, but I have the same problem on Windows). The images show the Texel engine, but I have the same problem - well, slightly different moves are played, but always the _same_ moves - if I use DeepTonga.
![1](https://cloud.githubusercontent.com/assets/9998846/22613580/5663366c-ea71-11e6-9417-d44d07616090.png)
![2](https://cloud.githubusercontent.com/assets/9998846/22613589/682dca92-ea71-11e6-97aa-8a577a48abf4.png)
![3](https://cloud.githubusercontent.com/assets/9998846/22613591/6b23b5e0-ea71-11e6-937c-2702504ec0bb.png)
![4](https://cloud.githubusercontent.com/assets/9998846/22613592/6d1f2fbe-ea71-11e6-9e4c-d9ce4e46c411.png)

**Comment by lukasmonk** [comment]
The Texel log is the next:
Lines with "put >>>", are orders from GUI to engine, the rest all are output of engine

> put>>> uci
> id name Texel 1.05 32-bit
> id author Peter Osterlund
> option name UCI_EngineAbout type string default Texel 1.05 32-bit by Peter Osterlund, see http://web.comhem.se/petero2home/javachess/index.html#texel
> option name Hash type spin default 16 min 1 max 524288
> option name OwnBook type check default false
> option name Ponder type check default true
> option name UCI_AnalyseMode type check default false
> option name Strength type spin default 1000 min 0 max 1000
> option name Threads type spin default 1 min 1 max 64
> option name MultiPV type spin default 1 min 1 max 256
> option name GaviotaTbPath type string default 
> option name GaviotaTbCache type spin default 1 min 1 max 2047
> option name SyzygyPath type string default 
> option name MinProbeDepth type spin default 1 min 0 max 100
> option name Clear Hash type button
> uciok
> put>>> setoption name Hash value 32
> put>>>  setoption name Ponder value false
> put>>>  setoption name MultiPV value 256
> put>>> isready
> readyok
> put>>> position startpos
> put>>> isready
> readyok
> put>>> go depth 3
> info depth 1
> info depth 1 score cp 2 time 1 nodes 1 nps 1000 pv b1a3
> info depth 1 score cp 39 time 1 nodes 2 nps 2000 pv b1c3
> info depth 1 score cp 53 time 1 nodes 3 nps 3000 pv g1f3
> info depth 2
> info depth 2 score cp 14 upperbound time 1 nodes 23 nps 23000 pv g1f3 b8c6
> info depth 2 score cp 0 time 1 nodes 44 nps 44000 pv g1f3 g8f6
> info depth 3
> info depth 3 score cp 16 lowerbound time 1 nodes 111 nps 111000 pv g1f3 g8f6 b1c3
> info depth 3 score cp 32 lowerbound time 1 nodes 135 nps 135000 pv g1f3 g8f6 b1c3
> info depth 3 score cp 46 time 1 nodes 183 nps 183000 pv g1f3 g8f6 d2d3
> info nodes 213 nps 213000 time 1
> bestmove g1f3 ponder g8f6

g1f3 = Nf3 is the decision of engine, nothing to do by the GUI.
If you want an standard opening, you could select a book by example and change Opponent's move option.

The reason to select always Nf3 by Texel is the use of a fixed depth.

But something is wrong, because if you select intermediate level then the engine must work in analysis mode, I will fix it.

**Comment by fonkap** [comment]
Hi, I'd like to help with this issue if I can.
@ACinnamonUserInUK , I'm confused, you say in the text DeepTonga (DeepToga?) But in the pictures Texel engine is shown. 
Which one are you trying? 
You are using the exact configuration shown in the pictures?
Would it be possible to know which previous version that you mentioned, worked as you expected?

Thanks.

**Comment by ACinnamonUserInUK** [comment]
Dear fonkap

That's good of you; but I think a bug has been acknowledge and is being
worked on. (See Lucas Monk's comment in the post above: 'But something
is wrong, because if you select intermediate level then the engine must
work in analysis mode, I will fix it.')

Still, here is the explanation of the discepancy that you noticed. I did
say that Deep Toga (well, I wrote 'Deep Tonga', but I meant Deep Toga)
was subject to the problem, but I think I said also that other of the
chess engines were too - and, certainly, Texel is too.

I know that previously Deep Toga worked. I don't know about Texel; for,
I hadn't tried Texel until I started having problems.

**Comment by lukasmonk** [comment]
This issue has served me to find an error but without a relation to the problem exposed, this error is fixed in my local code. Error = when MultiPV is active (in this case it is activated when option Set strength is other than best move, Intermediate in this case), then if engine like **texel** has an **UCI_AnalyseMode** option, it must be set to true to work properly.

Texel  with fixed depth 3 **without using a book**, in all cases move **Nf3**.
It is not necessary to use the Gui to test, running the texel.exe and writing "go depth 3", in all my tries bestmove = g1f3.

When the error was fixed in the public release, in this particular case (where Set strength=Intermediate ) then the result will be other than Nf3, because the GUI select other moves of the list of moves presented (MultiPV) by the engine, but in this list Nf3 will be the bestmove again (because depth 3).

**Comment by lukasmonk** [comment]
In the case of Toga, with depth = 3 and  Set strength=Intermediate:

1. Set strength=Intermediate has the effect of setting MultiPV to 40
2. Fixed depth 3, in Toga the MultiPV service is not active with this fixed depth.
3. It select always with these conditions Nf3(bestmove). The gui does not decide the move, since it only shows one option.

With Set strength=Intermediate, it is better to select a fixed time than a fixed depth, because the limitation of power of the engine is done by the GUI. The engine select a list of moves with evaluations, the GUI select a move that has an eval less than bestmove.

**Comment by LinuxOnTheDesktop** [comment]
If I might add to this closed report . . The following

> In the case of Toga, with depth = 3 and Set strength=Intermediate:
> 
>     Set strength=Intermediate has the effect of setting MultiPV to 40
>     Fixed depth 3, in Toga the MultiPV service is not active with this fixed depth.
>     It select always with these conditions Nf3(bestmove). The gui does not decide the move, since it only shows one option.
> 
> With Set strength=Intermediate, it is better to select a fixed time than a fixed depth, because the limitation of power of the engine is done by the GUI. The engine select a list of moves with evaluations, the GUI select a move that has an eval less than bestmove.
> 

is, surely, much more complicated that it needs to be. Surely, users should not have to know this. Rather, they should be able to get some randomization - or perhaps, the lack of it, if they wish - just by pressing a few buttons. They should not have to know how the internals work. All in all, I think that a change here would greatly improve LucasChess.

**Comment by lukasmonk** [comment]
I am working in the next version. This window is changed to:
![image](https://user-images.githubusercontent.com/6254278/73131066-af1a3a80-4004-11ea-974f-89e0ea556bad.png)
The Advanced tab:
![image](https://user-images.githubusercontent.com/6254278/73131086-dec94280-4004-11ea-9545-5f077e74529f.png)
