### ISSUE TITLE
Better bug logging (immediate saving).

### ISSUE THREAD

**Issue by tico-tico** [lukasmonk/lucaschess#30]
For now tracebacks are flushed to disk only after you close the program. It really inconvenient for catching bugs. All tracebacks should be saved immediately. When I played with https://github.com/lukasmonk/lucaschess/issues/29 I had to make some changes to **Init.py**.

```python
DEBUG = False
VERSION = "10.11"

import os
import sys

from Code.Constantes import *

if DEBUG:
    prlkn("DEBUG " * 20)

from Code import VarGen
from Code import Procesador
from Code import Sonido

from Code.QT import Gui

class loghelper:
    def __init__(self, logname):
        self.logname = logname
    def write(self, buf):
        ferr = open(self.logname, "at", 0)
        ferr.write(buf)
        ferr.close()

def init():
    if not DEBUG:
        sys.stderr = loghelper("bug.log")

    mainProcesador = Procesador.Procesador()
    mainProcesador.setVersion(VERSION)
    runSound = Sonido.RunSound()
	
[...snip...]

And remove this
    if not DEBUG:
        if okFerr:
            ferr.close()

[...snip...]
```

But I'm really bad at Python so I guess you can invent better solution.

**Comment by lukasmonk** [comment]
I use prints to do fast debug.

PyCharm show all of the prints when working.
SciteRu is my fast editor and also show prints.

**Comment by tico-tico** [comment]
Yes, but the average user can't say "I get the traceback if I click this or if I click that" since the *bug.log* is populated only after the program is closed. Now it impossible to say which action exactly leads to traceback. Anyway, it's up to you of course.

**Comment by lukasmonk** [comment]
Till now, average user only think in bug.log, when I say him, please send me file bug.log in the root instalation of the program to fix the bug. :)

I have added Log class to util.py, and this call in init.py.

**Comment by tico-tico** [comment]
Something unrelated:

I just played with *bug.log* opened in Notepad++ in the monitoring mode and get this

```
Traceback (most recent call last):
  File "Code\QT\TabElementos.pyo", line 220, in mouseReleaseEvent
    
  File "Code\QT\Tablero.pyo", line 1284, in intentaMover
    
  File ".\Code\GestorEntMaq.py", line 793, in mueveHumano
    submenu.opcion("user", "%s (%s)" % (_("Select my move"), rmUser.abrTextoBase()),
AttributeError: 'NoneType' object has no attribute 'abrTextoBase'
```

after pawn promotion to queen. So immediate saving to *bug.log* is quite useful.))

**Comment by lukasmonk** [comment]
I have changed promotion to be always lowercase.

**Comment by tico-tico** [comment]
A can't see the exceptions any more so I guess the issues are fixed. Thanks!
