### ISSUE TITLE
fix for buggy Rodent 1.x as an external engine.

### ISSUE THREAD

**Issue by tico-tico** [lukasmonk/lucaschess#35]
Rodent 1.x (1.6, 1.7) have a broken output in UCI combo options. See this line break before **default GM**?

![rodentoutput](https://cloud.githubusercontent.com/assets/10702026/24082342/1e7f3b3e-0cd5-11e7-906a-59011aca9507.png)

Because of this, the parameter isn't shown in the LC's external engine config GUI.
Proposal fix (in *EngineThread.py*):

```python
    def xstdout_thread(self, stdout, lock):
        try:
            while self.working:
                line = stdout.readline()
                if not line:
                    break
                lock.acquire()
                if line.startswith(' default'): # fix for buggy rodent 1.x
                    self.liBuffer[-1] += line
                else:
                    self.liBuffer.append(line)
                lock.release()
        except:
            pass
        finally:
            stdout.close()  
```

I don't know if you OK to do it just for one engine (well, maybe two).

**Comment by lukasmonk** [comment]
Thanks tico, but it is only a problem of versión 1.7, program includes version 1.6.
It is bug of the engine, it is more easy to get the sources of this version and compile again.

**Comment by tico-tico** [comment]
> but it is only a problem of versión 1.7

Nope. Actually official Rodent 1.6 distribution (here http://www.pkoziol.cal24.pl/rodent/history.htm) has this issue in the **Strength** and **Book** combo.

> program includes version 1.6.

I'm talking about external engines. for people who want to use Rodent 1.x as-is.

> it is more easy to get the sources of this version and compile again.

yes, but it's not OK for people who download engines from the official sites.

**Comment by lukasmonk** [comment]
I believe that Pavel hasn´t problem to fix this engine.

The change suppouses that all lines read of any engine, must be checked against an start string, because an engine has a bug. 
If the problem was in several engines or in Komodo (by example-where there is not free sources), then the change is justified in my opinion.
