### ISSUE TITLE
Save tournaments PGNs

### ISSUE THREAD

**Issue by cja000** [lukasmonk/lucaschess#37]
Hi,

I have seen that when you save all the matches of a tournament to a PGN there is no blank line between games.
I don't know if I understand right the [PGN spec](https://www.chessclub.com/user/help/PGN-spec):

> 8.2.1: Movetext line justification
> ...
> As with the tag pair section,
> a single empty line follows the last line of data to conclude the movetext
> section.
> ...

I guess that including a '\n' in the file `Code\Torneo.py` could do it:

```
def pgn(self, torneo):
...
    return cabecera + "\n" + base + " %s\n\n" % rs
```

Br

**Comment by lukasmonk** [comment]
Added in my copy.
Thank you very much.

**Comment by cja000** [comment]
Sorry I forgot to include the double '\n' in the cabecera part also.

```
def pgn(self, torneo):
...
    return cabecera + "\n\n" + base + " %s\n\n" % rs
```

**Comment by lukasmonk** [comment]
I believe that it is not necessary, but I will test it.
On the other hand, there are something wrong saving several games. I´ll try to fix it.
