### ISSUE TITLE
Turn On The Lights not accepting alts

### ISSUE THREAD

**Issue by mart0258** [lukasmonk/lucaschess#40]
Interception-blocade.fns:19 has a solution of 1.Re8+ Bxe8 2.Qg8#, but Lucas Chess rejects this in the Turn On the Lights exercise..  

This appears to be a two-part issue, first is that the .fns file doesn't have the alt listed, and second is that it isn't recognized by that activity even if the alt is present.

**Comment by lukasmonk** [comment]
1. "The .fns file doesn't have the alt listed", yes, and I prefer not change it to maintain the original idea of the teacher that creates them.
2. Turn on the light is a game with the speed in mind, and alternatives are not supported.
