### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by DrDonkey** [lukasmonk/lucaschess#44]
I don't think it is usable on linux.
Though it can be used in winE.
But generic support would be great.
Thanks.

**Comment by lukasmonk** [comment]
lucaschess_11 has more support to Linux.
[https://github.com/lukasmonk/lucaschess_11](https://github.com/lukasmonk/lucaschess_11)

**Comment by DavidParkin** [comment]
I can't get it to work on native Linux. The play against engine of choice starts, accepts my move but never responds. After this the interface widgets do not always work.

**Comment by lukasmonk** [comment]
Test chmod to 777 to all folders below Engines folder.

**Comment by DavidParkin** [comment]
All file and folders below Engines set to perm 777 - still does not work.

**Comment by lukasmonk** [comment]
Sorry, I always forget that the support of Linux is in the new version (in development) https://github.com/lukasmonk/lucaschess_11.

**Comment by DavidParkin** [comment]
Sorry, I should have said that I am using version 11.

**Comment by DavidParkin** [comment]
Does this help?
Traceback (most recent call last):
  File "./Code/QT/TabElementos.py", line 220, in mouseReleaseEvent
  File "./Code/QT/Tablero.py", line 1308, in intentaMover
  File "./Code/GestorEntMaq.py", line 771, in mueveHumano
  File "./Code/GestorEntMaq.py", line 558, in analizaFinal
  File "./Code/Gestor.py", line 874, in analizaTutor
  File "./Code/XGestorMotor.py", line 160, in analiza
  File "./Code/XGestorMotor.py", line 81, in testEngine
  File "./Code/XMotor.py", line 37, in __init__
  File "./Code/EngineThread.py", line 113, in start
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by zagabra** [comment]
hello, thanks for lucaschess...i think the best software of that kind..
i have a little problem..:
inlinux mint i try it with wine but every move i do in the excercise (like mate in one) give me the message of wrong move (even if the move is right...).. i try the linux one... (i follow the istruction but do not start.. with xmk_linux nothing happen.. i cry a lot...

**Comment by lukasmonk** [comment]
This is a bug I will fix in this weekend.

**Comment by lukasmonk** [comment]
Fix =
File: Code/GestorMate
Line: 451
Change: jg.siJaqueMate  --->    jg.siJaque    (remove Mate)

**Comment by TheDumbKnight** [comment]
Found lucaschess in [AUR](https://aur.archlinux.org/), installed it.
Seems quite laggy.
Less configurations.
What is [this](https://kek.gg/i/44vC9M.png)?(i am using i3wm)

Is right clicking and dragging to create arrows not available?

**Comment by lukasmonk** [comment]
This is Challenge 101, 10 positions, only one move is valid, you move.... play if you want

You must press F1/../F10 then create your own arrows, blocks, ......  (if you don´t have arrows: right button on F1 box, Edit, Arrows, then create one arrow, right button on F1 box again, Arrows, select the arrow created) with left button.....

**Comment by TheDumbKnight** [comment]
I meant at the rightmost of screen. Quite many blinking happening in about everything. I like the tactics training. How many tactics are there?

**Comment by lukasmonk** [comment]
Program only controls left part.

To train tactics there are some options, the presentation:challenge 101, Training positions, Mates, Training tactics by repetition, Turn on lights, ....

**Comment by TheDumbKnight** [comment]
Can you disable right click to show game comments?? and enable arrows on right click and drag?

**Comment by zagabra** [comment]
@TheDumbKnight 
i have installed exe version 11.03 and its perfect

**Comment by TheDumbKnight** [comment]
@zagabra using winE??

**Comment by zagabra** [comment]
yes, work perfectly with wine from repository or also lastest stable from their website (i try both)

**Comment by TheDumbKnight** [comment]
Let me try the exe version, be right back.

**Comment by Costor** [comment]
1) Lucas Chess runs natively under Linux - see #51 . May be the installation process should become more polished...

2) Yes, at least the portable windows version 11.04a runs perfectly using current wine version.
