### ISSUE TITLE
Board size not available anymore Options/Configuration/Boards

### ISSUE THREAD

**Issue by fab672000** [lukasmonk/lucaschess#46]
Used to be able to change board size but in 10.12a the popup menu is gone from  Options/Configuration/Boards, is there another way to do it ?

**Comment by lukasmonk** [comment]
All boards can be resized, with right button in the left-up corner, it shows a menu with that option.

**Comment by fab672000** [comment]
Just noticed that right-clicking anywhere on the board borders will also make this special menu to popup.
Thank you.
