### ISSUE TITLE
Portable version contatins much more options in training than installed version?

### ISSUE THREAD

**Issue by ChameleonRed** [lukasmonk/lucaschess#47]
I installed by accident portable and windows version and saw that portable version contains much more training material that installation. Can you fix it or explain how to fix installed version?

**Comment by lukasmonk** [comment]
I've checked that they're the same (version 10.13).
I have just downloaded both, installed them, removed the uninstaller from the installable version, and both occupy exactly: 175,649,774 bytes.

There is other version, the development version, that has more material, more engines, ....

**Comment by ChameleonRed** [comment]
Thanks you for answer. I found difference I have 10.13 (installed) and 11.00.21b (portable) - no idea for where I downloaded second. I am very good Python programmer (not only Python) and playing chess. Program is very advanced and looks good.

**Comment by ChameleonRed** [comment]
See it is my portable version information: 

Wersja 11 | Nils Andersson, vga, Alfonso Solbes, Rob, Ed Smith, Max Aloyau, Giovanni di Maria, Bernhard, tico-tico
-- | --

**Comment by lukasmonk** [comment]
From time to time I think about redoing the code, converting the tags to English, and also rationalizing it. this would allow more people to join the project.
I also think about the conversion to python 3.6 and qt 5, I calculate all the work and I get discouraged. Maybe version 12 will make an attempt, but there are a lot of things to do and every day comes out new.
