### ISSUE TITLE
Clocks misbehave on suspend and resume

### ISSUE THREAD

**Issue by stolowski** [lukasmonk/lucaschess#5]
Game clocks misbehave when PC suspends and resumes, they are not paused. When I suspended my laptop in the middle of the game and resumed it an hour later, my clock was down to 0 and I lost on time immediately :/

Here is a hint about how this could be handled in Qt world:
http://stackoverflow.com/questions/7871284/qt-application-suspending

**Comment by lukasmonk** [comment]
The calculation time is very simple, time at end minus time at beginning.
User can use Adjourn option, and even better Pause button.
It is not easy to implement the support to suspends PC situation.
I add your message to the list of ideas of lc.
Thank you very much.

**Comment by stolowski** [comment]
I know it's not trivial, you would need to monitor application events (as suggested by stackoverflow answers) and pause the timer. 
Yeah, I later discovered 'Adjourn', so support for suspend/resume is not so critical, only nice to have. Thanks for adding it to the wishlist.
