### ISSUE TITLE
Linux: Installation issues solved + game hangs when engines are used solved

### ISSUE THREAD

**Issue by Costor** [lukasmonk/lucaschess#51]
Hi, thanks for the great work!

I have managed to install 11.04a on Linux 32-bit (with some issues, see below).
The game starts up and I can do options and trainings.
However it seems to hang immediately when a chess engine is used:
1) Play against Kids engine: Hangs (Black Hand) after choosing white or black, for any engine chosen.
2) compete: engines Roccinante, tutor mcbrain or stockfish: first 2-3 moves are alright but as soon it gets out of the book it hangs (Black hand).
Checking the process list I never found any process of a chess engine running. Maybe loading of engines fails. Maybe this has to do with the issues I had during Linux 32-bit installation:

My Installation installation process & issues:
1) System is an 32-bit ubuntu derived distro, modern (2017) kernel etc.
2) I followed the advice given in Linux/LinuxInstallation.md. However that file seems to be truncated on the 64-bit explanation and has no explanation on 32 bit at all.
3) I copied all files to /usr/local/share/lucaschess. In ./Engines I deleted all windows and linux 64 bit folders.  BTW:  In the linux32 bit folder, in cheng, there seems to be an 64-bit engine only.
4) I did the chmod 777
5) I ran the package install xlinux_install.sh  .  There I had two observations:
  a) it seems that pip should be called without sudo - with sudo there are warnings about different user and access rights
  b) the package python-chess was not available as an apt package. Actually it is a python module and I was able to identify it on e.g. pypi.org and install it using 'pip install python-chess'
6) I started using Linux/xlucas.sh  .  I got the runtime error in DBgames.py  xpv2pgn no member of LCEngine. To fix this I re-compiled LCEngine and libirina doing the steps indicated for 64-bit in LinuxInstallation.md plus running xcython_linux.sh:
- cd LCEngine/irina
- ./xmk_linux.sh
- cd LCEngine
- ./xcython_linux.sh   #copies over to Engines/_tools/Linux32..

7) After this lucaschess started up without any complaints, however it hangs as soon as an eninge is required.

**Comment by lukasmonk** [comment]
You could try the next change:
File: Code/EngineThread.py
line 132
below the line:         os.chdir(self.direxe)  # to fix problems with non ascii folders
add the next:
        if VarGen.isLinux:
            self.args[0] = os.path.join(self.direxe, self.args[0])

**Comment by Costor** [comment]
1) Hanging / Engines not starting solved:
The code above didn't do the trick, as it still produces a relative path. It worked when I changed it to an absolute path:

File: Code/EngineThread.py:
below the line 132
       ``` os.chdir(self.direxe)  # to fix problems with non ascii folders  ```

add these lines:
```
        if VarGen.isLinux:
            self.args[0] = os.path.join(os.path.abspath(os.curdir), self.args[0])
```
2)  "Play like a Grandmaster" crashes because of a capitalization mistake in file name:
In File Code/GM.py, line 196  
replace "gm/listaGM.txt"  by "GM/listaGM.txt"    

Also in GM/ , all files *.xgm need to be renamed to all lower case letters (otherwise GM.py will crash in line 71). Hopefully in the upcoming release Lucas might fix this in the code.

3) Linux installation issues solved. This should work for 32bit and 64 bit.
I modified the file ./Linux/xlinux_install.sh to this:

```
#!/usr/bin/env bash
# execute as an user who is member of the sudoers, i.e. can elevate to root
sudo apt-get install python-pip
# added next line to make sure to have most current pip version
pip install --upgrade pip
sudo apt-get install python-dev
sudo apt-get install python-qt4
sudo apt-get install python-pyaudio
# added install of setuptools, is required for psutils, python-chess and PhotoHash
pip install setuptools
pip install psutil
pip install pygal
pip install chardet
pip install python-chess
pip install Pillow
pip install PhotoHash
pip install Cython

# !! modify path to your installation directory of lucaschess!!
cd /usr/share/lucaschess

# give read rights to group and others
sudo chmod -R 755 *
# give execution right to all executable files, especially chess engines
sudo chmod -R +x *
# give all rights to ./UsrData in order for all users to share settings
sudo chmod 777 UsrData

# build Irina engine etc, refresh existing libirina.so and LCEngine.so
cd LCEngine/irina
./xmk_linux.sh
cd ..
./xcython_linux.sh 
```

**Comment by lukasmonk** [comment]
Thank you very much, I have updated my copy.

**Comment by Costor** [comment]
Regarding installation in Linux - two further remarks:
1) In order to have pip install python models for all users, sudo must be used. Otherwise models will be installed locally in /home/$USER/.lib/..somewhere...     
2) Read+Write permissions for ./UsrData must be extended to subdirectories also.

**So the complete installation process would be:**
As an user with sudo permission:
a) Unpack the lucaschess archive to eg. `/usr/share/lucaschess`
b) modify the existing shell script `/usr/share/lucaschess/xlinux_install.sh` as shown below  (take care to modify the installation path in the cd statement if it is not `/usr/share/lucaschess` )
c) execute `/usr/share/lucaschess/xlinux_install.sh`

```
#!/usr/bin/env bash
# execute as an user who is member of the sudoers, i.e. can elevate to root
sudo apt-get install python-pip
# added next line to make sure to have most current pip version
sudo pip install --upgrade pip
sudo apt-get install python-dev
sudo apt-get install python-qt4
sudo apt-get install python-pyaudio
# added install of setuptools, is required for psutils, python-chess and PhotoHash
sudo pip install setuptools
sudo pip install psutil
sudo pip install pygal
sudo pip install chardet
sudo pip install python-chess
sudo pip install Pillow
sudo pip install PhotoHash
sudo pip install Cython

# !! modify path to your installation directory of lucaschess!!
cd /usr/share/lucaschess

# give read rights to group and others
sudo chmod -R 755 *
# give execution right to all executable files, especially chess engines
sudo chmod -R +x *
# give all rights to ./UsrData in order for all users to share settings
sudo chmod +R 777 UsrData

# build Irina engine etc, refresh existing libirina.so and LCEngine.so
cd LCEngine/irina
./xmk_linux.sh
cd ..
./xcython_linux.sh
```
Now start lucaschess via `/usr/share/lucaschess/xlucas.sh`  .

**Comment by DrDonkey** [comment]
@Costor as you said in the comment above in step `b) modify the existing shell script /usr/share/lucaschess/xlinux_install.sh as shown below (take care to modify the installation path in the cd statement if it is not /usr/share/lucaschess )`
But the xlinux_install.sh is not in /lucaschess/ it is in /lucaschess/Linux/. So how does one proceed.

**Comment by DrDonkey** [comment]
Tried removing the `rm` line from the script. and tried bash xlucas.sh but came the following.
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 56, in <module>
    import Code.Init
  File "./Code/Init.py", line 4, in <module>
    from Code import Util
  File "./Code/Util.py", line 17, in <module>
    import scandir
ImportError: No module named scandir

**Comment by lukasmonk** [comment]
scandir is other library to install

pip install scandir

**Comment by lukasmonk** [comment]
LCEngine.so and Irina.so must be copied to /lucaschess/Engines/Linux<32 or 64>/_tools

**Comment by DrDonkey** [comment]
I installed scandir manually but it was installed for python 3 not for python 2. So that was cause of the error. So went [here](https://docs.python.org/2/installing/index.html) and then installed for the python 2.7. But now I have another problem. 
After running `bash xlucas.sh` i get

`x86_64`
`python2.7: can't open file './Lucas.py': [Errno 2] No such file or directory`

**Comment by Costor** [comment]
DrDonkey thanks for the comments; I updated my script above accordingly.
However as I'm new to Linux and am using a Debian/Ubuntu based distro I can only gues what is going on in other distros.

However some remarks:
1) Lucas chess is based on Python2.7  . There is a port to Python3 but all my comments referred to the main source, so all Python packages refer to Python 2.7.  I have no idea how to tell pip to fetch Python 2.7 packages and not for Python 3. 
2) python-Qt4, python-dev etc. packages -- I agree, it looks strange why these are installed by apt, and other python modules by pip. I took what Robert Gamble had written down in his initial comments Linuxinstallation.md as I was not sure what the right pip packages would have been instead.
3) Permissions on installations and building on all of lucaschess folder and subdir. But if you have copied the files there and are the owner, chmod -R 755 should give all rights...

./Linux/xcython_linux.sh  does the copying of ```Libirina.so``` and ```LCEngine.so```  to the correct subdirectory ```./Engines/Linux<nn>/_tools``` , so no manual copying is necessary.

4) "can't open file ./Lucas.py" is strange. Open a command line, ```cd``` to the lucaschess/Linux folder, and start by ``` ./xlucas.sh``` from there.

**Comment by Costor** [comment]
To Lucas: Is there a way to run Lucaschess in -Debug mode, so all error messages are dumped to the terminal? That would vastly simplify debugging in Linux as I assume there will be more issues like capitalisation etc. that are simple to pinpoint if a traceback is provided.

That is because I have not managed to find the bug.log file. The one in lucaschess/ is never updated.

**Comment by lukasmonk** [comment]
File init.py have a DEBUG = False, change it to True

**Comment by DrDonkey** [comment]
`./xlucas.sh` gives error as shown below:
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 56, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 7, in <module>
    from Code import Routes
  File "./Code/Routes.py", line 5, in <module>
    from Code import Partida
  File "./Code/Partida.py", line 2, in <module>
    from Code import ControlPosicion
  File "./Code/ControlPosicion.py", line 1, in <module>
    import LCEngine
ImportError: ././Engines/Linux64/_tools/LCEngine.so: undefined symbol: PyFPE_jbuf

**Comment by Costor** [comment]
DrDonkey,
probably LCEngine.so has not been created correctly.  Building it is done by (see above) a user who has appropriate rights to write into /usr/share/lucaschess :

```
# build Irina engine etc, refresh existing libirina.so and LCEngine.so
cd /usr/share/lucaschess
cd LCEngine/irina 
./xmk_linux.sh
cd ..
./xcython_linux.sh 
```
This will also copy libirina.so and LCEngine.so to the correct _tools directory!

If the problem prevails the python installation is probably mixed up? 

BTW: If you have the windows emulator wine installed: I have found that the portable windows version of lucaschess works fine with wine. Maybe that is an alternative for the moment.

**Comment by fafamonge** [comment]
I'm stuck with this installation. A lot of problems and now getting this:

```
rafael@ProBook:/usr/share/lucaschess/Linux$ ./xlucas.sh 
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 47, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 30, in <module>
    from Code import GestorRoutes
  File "./Code/GestorRoutes.py", line 11, in <module>
    from Code import LibChess
  File "./Code/LibChess.py", line 4, in <module>
    import chess
ImportError: No module named chess
```
My Python and PIP version:
```
rafael@ProBook:/usr/share/lucaschess/Linux$ pip --version
pip 19.1.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```
All modules and dependencies are installed:
```
rafael@ProBook:/usr/share/lucaschess/Linux$ pip freeze
apt-clone==0.2.1
apturl==0.5.2
beautifulsoup4==4.6.0
Brlapi==0.6.6
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
configobj==5.0.6
cupshelpers==1.0
Cython==0.29.9
defer==1.0.6
httplib2==0.9.2
idna==2.6
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
nemo-emblems==4.0.2
netifaces==0.10.4
onboard==1.4.1
PAM==0.4.2
pexpect==4.2.1
Photohash==0.4.1
Pillow==5.1.0
protobuf==3.0.0
psutil==5.4.2
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
pygobject==3.26.1
PyICU==1.9.8
pyinotify==0.9.6
pymacaroons==0.13.0
PyNaCl==1.1.2
pyRFC3339==1.0
python-apt==1.6.4
python-chess==0.28.0
python-debian==0.1.32
python-xapp==1.4.0
python-xlib==0.20
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
scandir==1.10.0
sessioninstaller==0.0.0
setproctitle==1.1.10
six==1.11.0
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.36
urllib3==1.22
xkit==0.0.0
```
I'm running Linux Mint 19.1 Cinnamon 86_64

**Comment by lukasmonk** [comment]
Current version is with python 2.7
