### ISSUE TITLE
Openings

### ISSUE THREAD

**Issue by emeikei** [lukasmonk/lucaschess#54]
Hi,

I like the openings from book.  It lets you play creatively within a solid framework.  The trouble is, I have no idea which opening I'm playing;  Or even if it is a standard opening variation at all.

The openings by repetition is ok if you want to practice specific variations.  But with so many variations on say the sicilian,  it's a pretty daunting task to even think of learning them all or even choosing which variations to learn first.

I'd like to pick a high level opening like the sicilian and have all the moves in the lower level variations at my (and my opponent's) disposal;  Just like openings from book does.   And when we move into a new variation, this could be indicated in the status bar.  This would allow us to explore the openings more creatively.

Of course, you could still pick specific variations to practice when you want to.

**Comment by lukasmonk** [comment]
I am working in a new way of study openings with tthe new option Opening lines. I´ll try to publish today if I can or this weekend. 
It has the option to import polyglot books, and to do trainings by repetition in three ways.

**Comment by emeikei** [comment]
I saw the reference to Opening Lines on the blog but I got the impression it was more geared to developing personal openings/variations.

I'll have a play with it.

Thanks.
