### ISSUE TITLE
Analysis: Flip the Board

### ISSUE THREAD

**Issue by emeikei** [lukasmonk/lucaschess#55]
When I analyse a game the graphics window always opens with white at the bottom.  So when I play black I always need to flip the board before playing through the game.

This is obviously not a big deal, but it would be nice if it opened up with the players colour at the bottom.

**Comment by lukasmonk** [comment]
I have fixed it in my copy.
Thanks.

**Comment by emeikei** [comment]
Brilliant.  Thanks.
