### ISSUE TITLE
x64 bmi2

### ISSUE THREAD

**Issue by emeikei** [lukasmonk/lucaschess#56]
The bmi2 engine versions crash my i5 system.  Wouldn't it be more compatible to have the plain x64 option.  And maybe a separate bmi2 option for those that can handle it.

Not a big deal at the moment because it only affects a couple of engines.  But in the future you may be using more 64bit engines.

**Comment by lukasmonk** [comment]
This is a personal prebend, on the other hand it is easy to add an external 64 bits engine for analysis.

**Comment by emeikei** [comment]
Not sure what you mean by 'prebend' but yeah, I use Stockfish 9 and Komodo so it's not a problem currently.  Just thinking of a possible future.

**Comment by lukasmonk** [comment]
I guess it is an spanglish term, I want to say that it is an option for my own personal benefit, since my i5 is compatible with bmi2. :)
