### ISSUE TITLE
expedition to everest

### ISSUE THREAD

**Issue by olpat59** [lukasmonk/lucaschess#57]
Lucas chess is a great job.
In the expedition of everest, with the 1106 version, after the engine has analized the move the game don't continue.

**Comment by lukasmonk** [comment]
Thanks, could you show bug.log? 
I am not able to replicate the problem, could you send me a sequence to do that replication.

**Comment by olpat59** [comment]
I send the two files:
bug.log
and
expedition.db
Is this enough? with the version 1012a all is fine.
Is this perhaps the new version of analize engine?
many thanks
Patrick Briguet
----Message d'origine----
De : notifications@github.com
Date : 02/03/2018 - 23:49 (CET)
À : lucaschess@noreply.github.com
Cc : briguetp@bluewin.ch, author@noreply.github.com
Objet : Re: [lukasmonk/lucaschess] expedition to everest (#57)
Thanks, could you show bug.log?
I am not able to replicate the problem, could you send me a sequence to do that replication.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lukasmonk/lucaschess","title":"lukasmonk/lucaschess","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lukasmonk/lucaschess"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lukasmonk in #57: Thanks, could you show bug.log? \r\nI am not able to replicate the problem, could you send me a sequence to do that replication."}],"action":{"name":"View Issue","url":"https://github.com/lukasmonk/lucaschess/issues/57#issuecomment-370075739"}}}

**Comment by lukasmonk** [comment]
Files ?

**Comment by olpat59** [comment]
here the files. i cannot upload expedition.db sorry!
[bug.log](https://github.com/lukasmonk/lucaschess/files/1777387/bug.log)

**Comment by lukasmonk** [comment]
Please test with version 11.06a, there is a problem with MultiPV and McBrain as it have changed the limits now different from stockfish and this version correct this.

**Comment by olpat59** [comment]
it's good with 1106a. thank you very much.
