### ISSUE TITLE
Tutor Too Hot

### ISSUE THREAD

**Issue by emeikei** [lukasmonk/lucaschess#58]
When starting a game that uses the tutor (fics-elo, engine of your choice, etc.), the engine runs permanently at 25% for internal 32bit engines or 99% for external engines that I've set to 4 threads. 

This is only since v11.06.

**Comment by emeikei** [comment]
I've tried older versions and it seems I was wrong, I'm having the same issue with those too.  Don't know why I didn't notice it sooner.

Can anyone else confirm this issue?

**Comment by lukasmonk** [comment]
Options-Configuration - Engines - Do not work in background when possible.

4 threads with a 4-cores processor is = 100%

If you use the engine alone, set it as 4 threads, you have a 100% of cpu used.

For instance:

MacBrain, launch the engine with Lucas, write:

setoption name Threads value 4 <intro>
go depth 30

and test the %cpu used.

**Comment by emeikei** [comment]
'Options-Configuration - Engines - Do not work in background when possible.' seems to work for fics-elo but not for 'play against engine of your choice'.

But why should this make any difference anyway?  In the tutor configuration tab I have 'duration of tutor analysis' set to 3 seconds.  Why would the tutor engine try to run full power continuously if it's only analysing for 3 seconds?

**Comment by lukasmonk** [comment]
'play against engine of your choice': user has Tutor thinks while you think, in the help tab.

3 second is treated as a minimum, it do the analysis all the time is allowed.

**Comment by emeikei** [comment]
> 3 second is treated as a minimum, it do the analysis all the time is allowed.
Ahh... ok.  That may explain why I get inconsistent analysis.

Thanks.
