### ISSUE TITLE
The number of read PGN games is off by one

### ISSUE THREAD

**Issue by stolowski** [lukasmonk/lucaschess#6]
I've noticed that the number of read games reported by PGN import tool is always off-by-one. I've verified this by creating a simple pgn file with just 2 games. Both were imported, but the status dialog reports 3 games. See the screenshot.

![screenshot from 2015-12-02 13 26 27](https://cloud.githubusercontent.com/assets/168604/11530883/941ccb7e-98f8-11e5-8536-763616dcbae8.png)

**Comment by lukasmonk** [comment]
Hi

I have fixed it now. To the next revision.

Thank you very much.

Cheers
Lucas

From:  Pawel Stolowski
Date:  2015-12-02 13:30
Subject:  [lucaschess] The number of imported PGN games is off by one (#6)
 
I've noticed that the number of games reported by PGN import tool is always off-by-one. I've verified this by creating a simple pgn file with just 2 games. Both were imported, but the status dialog reports 3 games. See the screenshot.
