### ISSUE TITLE
It is too easy to accidentally right-click, generating the extra pane to the right

### ISSUE THREAD

**Issue by CottonEaster** [lukasmonk/lucaschess#64]
On a laptop with a slightly dodgy touchpad, but also on a desktop with a mouse, it is very easy to unintentionally right-click and thereby suddenly shift the board to the left (and, indeed, accidentally shift it back). This is something that, I suspect, _will be irritating many users._ Please provide a menu option to disallow - or re-bind - this behaviour.

Lucas Chess, all versions, running both on Windows and on Linux under Wine.

PS: I mentioned this in a private e-mail. Probably here is a better place for the feedback.

**Comment by lukasmonk** [comment]
In the current update, it needs to press Ctrl and right mouse to launch Director.

**Comment by CottonEaster** [comment]
Well, if 'Director' is what I think it is, then that is just the thing! Great! But, 'the current update'. Is that the github version, or in the latest version of a downloadable installer, please?

**Comment by lukasmonk** [comment]
Director is that window that appears when Ctrl-Right.
With "current" I refers to version 11.07a (source, installable and portable), but the change to Ctrl-Right is done in 11.06 version.

**Comment by CottonEaster** [comment]
Thanks. I've installed 11.06 on Windows and on Linux (via Wine on the latter) and, indeed, right-click on its own does do anything. Admittedly, the png pane (if that's the right term - the pane with the moves list) is on automatically and seemingly unchangeably (whereas with the version I had before, right-click toggled it) but the main thing is that the screen no longer shifts on accidental right clicks. Thank you.
