### ISSUE TITLE
Colour configuration: 'by default' option is misleading

### ISSUE THREAD

**Issue by CottonEaster** [lukasmonk/lucaschess#65]
It's great that the colours are so configurable - and that configuration even works when the program runs on Linux under Wine. However, the 'by default' option seems to reset the colours to default, whereas one might equally well think that clicking it will _save one's custom choices_. So I customised my colours carefully and then pressed the button to 'set them as the default' and . . lost all the changes.

Suggestion: change the text to read, 'Reset to default'.

EDIT: actually, that 'by default' text - which, as I say, is a very ambiguous bit of English - appears many times within the configuration options.

**Comment by lukasmonk** [comment]
Changed, thank you very much.
