### ISSUE TITLE
Director graphics annotations wrong (mirrored) if board is rotated

### ISSUE THREAD

**Issue by stolowski** [lukasmonk/lucaschess#7]
I was entering an opening using Personal Opening Guide, having the board rotated (black at the bottom). After entering some annotations via Director (I marked weak squares on white's side of the board, as well as white's defense ideas) I closed the Director. After re-opening it the anotations I made were misplaced (mirrorded) on the director's board. I think this is because I started with rotated board. 

See the two screenshots. The 1st screenshot shows how the director displays the anootations incorrectly (not in sync with the main board). The second screenshot shows the correct behavior, but this is only working if the board is not rotated when Director gets opened.

![scr1](https://cloud.githubusercontent.com/assets/168604/11613171/be93fdb0-9c17-11e5-88b6-4847e775040c.png)
![scr2](https://cloud.githubusercontent.com/assets/168604/11613172/bea60f00-9c17-11e5-9bac-d3d0dbbb3ad7.png)

**Comment by lukasmonk** [comment]
Thanks, I´ll study it.

**Comment by lukasmonk** [comment]
Fixed by fonkap
