### ISSUE TITLE
The 'tutor' re-analyses your moves after you take a move back

### ISSUE THREAD

**Issue by CottonEaster** [lukasmonk/lucaschess#70]
(Tenative) Steps to reproduce:

with the tutor on, make a move (or perhaps it has to be one that the tutor faults);
take the move back (and perhaps one needs to do this not via the tutor pop-up window, but in the normal fashion);
the tutor then re-analyses the move, or at least something stalls the system.

Windows 8.1. Lucas Chess 11.07a

Screenshot (in case it is of use):

![image](https://user-images.githubusercontent.com/9998846/41742949-89291e42-7597-11e8-9628-1d352e50a6e4.png)

**Comment by lukasmonk** [comment]
Hi, I am unable to replicate the problem. Perhaps bug.log file has the error message.

**Comment by CottonEaster** [comment]
My bug.log contains, only, this:

> Version 11.08a
> Traceback (most recent call last):
>   File "Code\QT\WBase.pyo", line 283, in procesarAccion
>     
>   File "Code\GestorEntMaq.pyo", line 334, in procesarAccion
>     s
>   File "Code\Gestor.pyo", line 1278, in configurar
>
>  
>  File "Code\Gestor.pyo", line 902, in cambioTutor
>    
> AttributeError: GestorEntMaq instance has no attribute 'analizaTutorInicio'

**Comment by lukasmonk** [comment]
The information in the bug.log file seems to have nothing to do with the problem, but this allows to fix a small bug.

**Comment by CottonEaster** [comment]
I still have the same problem, reproduced this way: start playing a game; enable tutor; when the tutors faults you move, select 'take back'. At that point a whole CPU core gets used, seemingly indefinitely. This time (contrast above) I experienced the problem on Linux (using Wine and the 'McBrain' tutor).

Lucas Chess 11.09 and also on 11.10a (and, hey, the automatic, within-program update now works, even on Linux - that's good!).

**Comment by CottonEaster** [comment]
The problem persists in 11.14a. (I'd use the latest version, but it has worse problems, I find.)

**Comment by lukasmonk** [comment]
![image](https://user-images.githubusercontent.com/6254278/50728556-09abd480-112c-11e9-9f95-8dbfa50b58b2.png)

**Comment by CottonEaster** [comment]
Thanks, Lucas. However, I'm not seeing that menu.

**Comment by lukasmonk** [comment]
Please, send an screenshot

**Comment by CottonEaster** [comment]
The image (below) is from Linux, running LucasChess under Wine - because the screenshot software on my Windows 8 machine cannot capture tooltips. However, I see the same on both machines, i.e. a screenshot of the Windows machine would show the same stuff. Note also that clicking the 'takeback' button does not generate a menu. Note also please what I said about my LucasChess version number.

![image](https://user-images.githubusercontent.com/9998846/50738922-98722d00-11d0-11e9-811a-9c80aaa6ac85.png)

**Comment by lukasmonk** [comment]
In this screen tutor is disabled.
If tutor is enabled, it is necessary to know some variables:
In Tools - Configuration - Engines tab:
![image](https://user-images.githubusercontent.com/6254278/50739015-42a28280-11da-11e9-9e70-94239f3dbf9e.png)

When configuring the play:
![image](https://user-images.githubusercontent.com/6254278/50739042-7aa9c580-11da-11e9-98a5-abccad4878b9.png)

**Comment by CottonEaster** [comment]
**'Do not work in the background where possible'**: _off_, i.e. not ticked. (By the way, this option would be clearer / in better English were it: Work in the background, when possible', though that would invert the meaning of the value.)

**'The tutor thinks while you think'**: _off_, though clearly I have a bit of a theming problem here, as this screenshot shows:

![image](https://user-images.githubusercontent.com/9998846/50739146-feac7f00-11d3-11e9-8353-b08b05c21678.png)

**Comment by lukasmonk** [comment]
But is Tutor on or off when the problem is produced ?

Do not work in the background where possible: -> Work in the background, when possible: changed, thank you very much

**Comment by CottonEaster** [comment]
The settings I gave are the settings I use - so, I have the problem when I use the following settings.

'Do not work in the background where possible': off
'The tutor thinks while you think': off

Translation: glad to help.

**Comment by lukasmonk** [comment]
The only way to fix that problem is to replicate it in my PC, because of this I ask for all this data, as at the moment all test in my PC are correct, I am afraid that it is in relation to wine emulation.
Tutor options:
![image](https://user-images.githubusercontent.com/6254278/50740746-56a6ae00-11f3-11e9-8e7c-fa535568ab11.png)

**Comment by CottonEaster** [comment]
Dear Lucas

As I said above, I have the problem on *Windows* as well as Linux. Only the screenshot came from Linux - for reasons I explained. If you point me towards some good, free, Windows video recording software, then I'll record a video of the problem (on Windows).

**Comment by lukasmonk** [comment]
Perhaps: https://www.dvdvideosoft.com/products/dvd/Free-Screen-Video-Recorder.htm

Or: https://camstudio.org/   https://portableapps.com/apps/utilities/camstudio_portable

**Comment by CottonEaster** [comment]
I can no longer reproduce the problem. Some of the difficulty, I think, owes to LucasChess's interface (two configuration screens, unclarity about how the 'hints' relate to the tutor . .). Moreover, this report has become rather messy. I will close this bug report and try to reproduce this or similar bugs. If I manage to reproduce one, then I will open a new bug report. Thanks for the recorder links. Neither program works well but I could at least get the first one to run (once I'd disabled my firewall).
