### ISSUE TITLE
Impossible to create new root opening move after highlighting existing root node

### ISSUE THREAD

**Issue by stolowski** [lukasmonk/lucaschess#8]
It's a minor issue with Personal Opening Guide. When there is a root node of an opening, say "1. e4" then if you highlight it (click with a mouse), it's not possible to unselect it anymore and enter any new starting move on the root level of the tree (e.g. "1. d4").  Taking the 1. e4 move back by "Previous move" arrow button, or selecting "1.d4" from the "Summary of ..." panel do not help, because "1.e4" is still highlighted, and a node for "1.d4" root node cannot be created in the tree of moves.

The only workaround is to close Personal Op. Guide, open it again and enter "1.d4" move via the board immediately (i.e. making sure you don't highlight the existing "1. e4").

![zrzut ekranu 4](https://cloud.githubusercontent.com/assets/168604/11613235/1fed5636-9c1a-11e5-88d7-275883847c57.png)

**Comment by lukasmonk** [comment]
Thanks, I am working on it.

**Comment by lukasmonk** [comment]
![cats](https://cloud.githubusercontent.com/assets/6254278/11656541/33dd7c5a-9db6-11e5-8614-21d3315985b7.jpg)

**Comment by stolowski** [comment]
Ah, indeed, it works (and is not obvious ;)). Thanks!

**Comment by lukasmonk** [comment]
I will change the icon.
