### ISSUE TITLE
Maybe a Bug: Some external engines don't appear in the analysis configuration

### ISSUE THREAD

**Issue by Hamyz** [lukasmonk/lucaschess#81]
I have actually added some engines as external engines, but some of them(more specifically, lc0) don't appear in the list of eligible engines, but others (as Stockfish dev and Komodo) appear normally.

**Comment by lukasmonk** [comment]
Lc0 does not have the option UCI: MultiPV, which is necessary to be able to analyze or serve as a tutor.
You can play against it and you can also create a kibitzer based on it.

**Comment by Hamyz** [comment]
Thank you, and sorry wasting your time.
