### ISSUE TITLE
Edit board feature?

### ISSUE THREAD

**Issue by jeroenmeulenaar** [lukasmonk/lucaschess#88]
Is there an option somewhere to edit the board (place pieces wherever I want them) and then run analysis on that position? I don't always have a FEN/PGN of the position I want to analyse.

(I'm not sure if this is the best place to ask, but I couldn't find anywhere else)

**Comment by lukasmonk** [comment]
From Tools-Create your own game-Config-Start position.
If the position is in a image in a pdf/web... youcould use the scanner option.

You can always write to me at lukasmonk at gmail.

**Comment by jeroenmeulenaar** [comment]
This was indeed the option I was looking for. I think I mentally mapped "start position" to "put the board back to the starting position" and therefore never clicked this button. Thank for your quick reply (and great software)!

To me it would be clearer if the button would be called "edit position" or even "edit start position".
