### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by MicMicMon** [lukasmonk/lucaschess#89]
HTTPS seems to be broken on the website, when I click on download "Portable" or "Installable", firefox refuses to load the file with an HTTPS error "SSL_ERROR_NO_CYPHER_OVERLAP".

A quick look around seems to indicate the SSL protocol version for the server is out of date.

The guilty server looks to be: d29vzk4ow07wi7.cloudfront.net.

Any clue?

**Comment by lukasmonk** [comment]
It is a particular issue of Firefox:
https://support.mozilla.org/es/questions/1076594
https://wiki.mozilla.org/Firefox/Shield/Heartbeat

**Comment by MicMicMon** [comment]
Well, actually it wasn't this problem (I tried with other browsers), it really was an issue with the SSL certificate being wrong.
But it works ok now, it must have been a temporary glitch.
Thanks for looking into it.
