### ISSUE TITLE
scrolling PGN

### ISSUE THREAD

**Issue by mvkrdndm** [lukasmonk/lucaschess#9]
hello when scrolling with middle mouse it is confusing.
1-when cursor on area A you had to scroll top to go forward at pgn
2-when cursor on area B you had to scroll down to go forward at pgn
3-when cursor on the outside of the area A and B nothing happens if you scroll
this is confusing.my suggestion is it is one way and regardless the cursor on which area.and i assume standart way of doing this it should be if you scrool down pgn should go forward like chessbase products

![image 001](https://cloud.githubusercontent.com/assets/16892782/14795154/d5c6c85a-0b2f-11e6-9a8a-307718b84bf9.jpg)

**Comment by lukasmonk** [comment]
To the future 10 release, some time ago, I changed the program to match the behavior on the table PGN and on the board. 
Sorry, I don´t know if new behaviour is the same as chessbase products, this is not a factor in my decisions.

I note the point 3 to study.

Thank you very much.
