### ISSUE TITLE
Unable to promote pawn to Queen; Rook works

### ISSUE THREAD

**Issue by Stochastic13** [lukasmonk/lucaschess#96]
Here is the game I was playing as white. For `pawn f8` I get the drop down for promoting it, but when I click on Queen, the pawn just resets to `f7` without the turn having been played. It works if I promote it to Rook. 

**Details of the system**: Windows 10 i7; using LUCAS portable 11.15

**Game details**: Opponent - **Cheng 4 0.39 (900)**, Tutor - **Mccain 10.1 32bit(tutor)**, white's move number - **44**

Should I also share the previous moves/any further details?

![image](https://user-images.githubusercontent.com/28253514/52738003-aeef7d80-2ff3-11e9-868e-7ab0f693a284.png)

**Comment by lukasmonk** [comment]
Fixed, thank you very much.

**Comment by Stochastic13** [comment]
Did you also make a commit here, so as to close the issue and reference it?

**Comment by lukasmonk** [comment]
Maybe on Sunday I'll post a new update.

**Comment by lukasmonk** [comment]
Published
